ccflags-$(CONFIG_VIDEO_MXC_OUTPUT_DEBUG) += -DDEBUG

mx27_output-objs			:= mx27_v4l2_output.o mx27_pp.o
obj-$(CONFIG_VIDEO_MXC_EMMA_OUTPUT)	+= mx27_output.o 

obj-$(CONFIG_VIDEO_MXC_IPU_OUTPUT)	+= mxc_v4l2_output.o
